In [1]:
import pandas as pd
import numpy as np



In [2]:
# Set format display values in PD
# Se especifica que el maximo de decimales
pd.options.display.float_format = '{:,.2f}'.format
np.set_printoptions(precision=2)

In [4]:
# np.random.rand(filas,columnas)
# Genera numeros aletarios entre 0 y 1
x1 = np.random.rand(2, 5) * 100
print(x1)
x2 = np.random.rand(2, 5) * -100
print(x2)



[[78.15 39.77 68.5  98.82 55.42]
 [61.29 32.34 61.8  78.41 66.97]]
[[-41.11 -92.65 -97.4  -42.01 -80.53]
 [-30.25 -42.12 -14.93 -71.11 -68.26]]


In [5]:
# np.concatenate([matriz1, matriz2], axis=0)
# permite concatenar multiples matrices
# axis = 0 filas | 1 columnas
x_concatenate = np.concatenate([x1, x2], axis=0)
print(x_concatenate)

serie1 = pd.Series(x1[0], index=['a', 'b', 'c', 'd', 'e'])
print(serie1)

serie2 = pd.Series(x2[0], index=['c', 'd', 'e', 'f', 'g'])
print(serie2)

[[ 78.15  39.77  68.5   98.82  55.42]
 [ 61.29  32.34  61.8   78.41  66.97]
 [-41.11 -92.65 -97.4  -42.01 -80.53]
 [-30.25 -42.12 -14.93 -71.11 -68.26]]
a   78.15
b   39.77
c   68.50
d   98.82
e   55.42
dtype: float64
c   -41.11
d   -92.65
e   -97.40
f   -42.01
g   -80.53
dtype: float64


In [6]:
# pd.concat([serie1, serie2], axis=0)
# permite concatenar series
# axis=0 filas | 1 columnas
series_concat = pd.concat([serie1, serie2])
print(series_concat)

dataframe_1 = pd.DataFrame(np.random.rand(3, 2) * 10, columns=['a', 'b'])
print(dataframe_1)

dataframe_2 = pd.DataFrame(np.random.rand(3, 2) * -10, columns=['a', 'b'], index=[2, 3, 4])
print(dataframe_2)

a    78.15
b    39.77
c    68.50
d    98.82
e    55.42
c   -41.11
d   -92.65
e   -97.40
f   -42.01
g   -80.53
dtype: float64
     a    b
0 5.76 8.63
1 6.49 9.19
2 7.29 1.26
      a     b
2 -3.87 -7.07
3 -9.65 -2.35
4 -1.91 -4.51


In [7]:
# pd.concat([dataframe_1, dataframe_2], axis=0)
# concatena
# axis=0 filas | 1 colomunas
dataframes_concat = pd.concat([dataframe_1, dataframe_2], axis=0)
print(dataframes_concat)

# Otra forma de concatenar dataframe
other_way_concat = dataframe_1.append(dataframe_2)
print(other_way_concat)

# Trasnponiendo un DF
print(other_way_concat.T)


      a     b
0  5.76  8.63
1  6.49  9.19
2  7.29  1.26
2 -3.87 -7.07
3 -9.65 -2.35
4 -1.91 -4.51
      a     b
0  5.76  8.63
1  6.49  9.19
2  7.29  1.26
2 -3.87 -7.07
3 -9.65 -2.35
4 -1.91 -4.51
     0    1    2     2     3     4
a 5.76 6.49 7.29 -3.87 -9.65 -1.91
b 8.63 9.19 1.26 -7.07 -2.35 -4.51


In [9]:
# Merge

df_left = pd.DataFrame(
    {'X': ['x0', 'x1', 'x2', 'x3'],
     'W': ['w0', 'w1', 'w2', 'w3'],
     'Y': ['y0', 'y1', 'y2', 'y3']},
    index=[0, 1, 2, 3])

df_right = pd.DataFrame(
    {'Z': ['z2', 'z3', 'z4', 'z5'],
     'A': ['a2', 'a3', 'a4', 'a5'],
     'Y': ['y2', 'y3', 'y4', 'y5']},
    index=[2, 3, 4, 5])

# .merge(pd1, pd2)
# hace el match por el indice que tengan en comun
print(pd.merge(df_left, df_right))

# Especificando que tipo de union se requiere y por que llave indice se debe hacer el cruce
print(pd.merge(df_left, df_right, how='inner', on='Y'))

    X   W   Y   Z   A
0  x2  w2  y2  z2  a2
1  x3  w3  y3  z3  a3
    X   W   Y   Z   A
0  x2  w2  y2  z2  a2
1  x3  w3  y3  z3  a3
